# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8908fb7c50e2ca74712085fd3067f27da996d1d92543dd1a6b9aae9c89ab574f224f764b0f19626e4ab1e3a528e792eb608fba51373f104057dff71b6a6112ec

test:
  secret_key_base: 0c60438a633f884b593008256f6efda8d72328d607d828a145c802ddd840132405e9a0eb4bad0d798f405f4dd90b95e6346a413ffb421484e4dbb98fa92cd8dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
